INSERT INTO public.departments (name) VALUES
  ('CTO'),
  ('SPD'),
  ('FCOV'),
  ('CEVC1'),
  ('CEVC2'),
  ('STVC - R&D'),
  ('CEVC2 - CySS'),
  ('FCOV - LRM'),
  ('CEVC2 - System'),
  ('OPDC - HRF'),
  ('CEVC1 - DSV - UI/UX 1'),
  ('CEVC1 - DSV'),
  ('CEVEC'),
  ('OPDC - HRD - C&C'),
  ('STVC'),
  ('FCOV - F&A'),
  ('CEVC1 - DSV - UI/UX 2'),
  ('CEVC1 - AIE'),
  ('OPDC - HRF - C&B'),
  ('FCOV - GA'),
  ('FCOV - ISO'),
  ('STVC - EE'),
  ('GEU - HUST'),
  ('CEVEC - SAPD'),
  ('OPDC - HRF - OD'),
  ('CEVEC - GSD'),
  ('GEU - TM'),
  ('STVC - R&D - DTR'),
  ('STVC - R&D - DPS'),
  ('CEVC3'),
  ('STVC - R&D - AIR'),
  ('CEVC4'),
  ('PAO'),
  ('GEU'),
  ('GEU - DUT'),
  ('OPDC - HRD - L&D'),
  ('OPDC - HRD - TI'),
  ('OPDC - HRF - TA'),
  ('GEU - UET'),
  ('STVC - R&D - SDX'),
  ('OPDC - HRD - HRBP'),
  ('PAO - PEC'),
  ('IAV'),
  ('STVC - Infra'),
  ('CPV - CGP'),
  ('GEU - UIT'),
  ('OPDC - HRD'),
  ('BDV'),
  ('CPV'),
  ('PAO - PAO')
ON CONFLICT (name) DO NOTHING;
